=== yuanxuegui/exhibition.models.common4Java/src/main/resources/exhibition-1.2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.sec.ac.cn/exhibition-1.2"
	xmlns:tns="http://www.sec.ac.cn/exhibition-1.2" elementFormDefault="qualified">

	<element name="exhibition" type="tns:exhibition"></element>

	<complexType name="exhibition">
		<sequence>
			<element name="description" type="string"></element>
			<choice maxOccurs="unbounded">
				<element name="property" type="tns:property"></element>
			</choice>
			<choice maxOccurs="unbounded">
				<element name="area" type="tns:area"></element>
			</choice>
		</sequence>
	</complexType>


    <complexType name="property">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>
    
    <complexType name="area">
    	<sequence>
    		<choice maxOccurs="unbounded">
    		<element name="device" type="tns:device"></element>
    	</choice>
    		<element name="timeline" type="tns:timeline"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>
    
    
    <complexType name="timeline">
    	<sequence>
    		<choice maxOccurs="unbounded">
    		<element name="property" type="tns:property"></element>
    	</choice>
    		<choice maxOccurs="unbounded">
    		<element name="timePoint" type="tns:timePoint"></element>
    	</choice>
    	</sequence>
    </complexType>
    
    <complexType name="device">
    	<choice maxOccurs="unbounded">
    		<element name="operation" type="tns:operation"></element>
    	</choice>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="CURTAIN"></enumeration>
    				<enumeration value="LIGHT"></enumeration>
    				<enumeration value="SOMKE"></enumeration>
    				<enumeration value="WATER"></enumeration>
    				<enumeration value="FOG"></enumeration>
    				<enumeration value="SHADOW"></enumeration>
    				<enumeration value="PC"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    
    <complexType name="operation">
    	<choice maxOccurs="unbounded">
    		<element name="parameter" type="tns:parameter"></element>
    	</choice>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="command" type="string" use="required"></attribute>
    </complexType>

    <complexType name="parameter">
    	<attribute name="type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="BOOLEAN"></enumeration>
    				<enumeration value="INTEGER"></enumeration>
    				<enumeration value="DECIMAL"></enumeration>
    				<enumeration value="STRING"></enumeration>
    				<enumeration value="DATE"></enumeration>
    				<enumeration value="TIME"></enumeration>
    				<enumeration value="DATETIME"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="minValue" type="string" use="optional"></attribute>
    	<attribute name="maxValue" type="string" use="optional"></attribute>
    </complexType>

    <complexType name="timePoint">
    	<choice maxOccurs="unbounded">
    		<element name="command" type="tns:command"></element>
    	</choice>
    	<attribute name="tick" type="int"></attribute>
    </complexType>

    <complexType name="command">
    	<choice maxOccurs="unbounded">
    		<element name="property" type="tns:property"></element>
    	</choice>
    	<attribute name="deviceId" type="string"></attribute>
    	<attribute name="operationName" type="string"></attribute>
    </complexType>
</schema>

=== yuanxuegui/exhibition.models.common4Java/src/main/resources/exhibition-1.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<exhibition xmlns="http://www.sec.ac.cn/exhibition-1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sec.ac.cn/exhibition-1.2 exhibition-1.2.xsd ">
  <description>某展示会</description>
  <property name="server.ip" value="192.168.1.2"/>
  <property name="server.port" value="9090"/>
  <area name="展区1">
    <device id="展区1-PC-1" type="PC">
      <operation command="$PC KEY {deviceId} {key}#" name="键值">
        <parameter name="key" maxValue="z" minValue="a" type="STRING"/>
      </operation>
      <operation command="$PC PLAY {deviceId} {cmd}#" name="播放">
        <parameter name="cmd" maxValue="4" minValue="1" type="INTEGER"/>
      </operation>
    </device>
    <device id="展区1-LIGHT-1" type="LIGHT">
      <operation command="$LIGHT ON {deviceId} {onoff}#" name="开关灯">
        <parameter name="onoff" maxValue="1" minValue="0" type="BOOLEAN"/>
      </operation>
      <operation command="$LIGHT {deviceId} {val}#" name="亮度">
        <parameter name="val" maxValue="100" minValue="0" type="INTEGER"/>
      </operation>
    </device>
    <timeline>
      <property name="unit" value="s"/>
      <property name="max" value="40"/>
      <timePoint tick="0">
        <command deviceId="展区1-PC-1" operationName="键值">
          <property name="key" value="b"/>
        </command>
      </timePoint>
      <timePoint tick="1">
        <command deviceId="展区1-PC-1" operationName="播放">
          <property name="cmd" value="2"/>
        </command>
      </timePoint>
      <timePoint tick="2">
        <command deviceId="展区1-LIGHT-1" operationName="开关灯">
          <property name="onoff" value="1"/>
        </command>
      </timePoint>
    </timeline>
  </area>
  <area name="展区2">
  	<device id="展区2-PC-1" type="PC">
      <operation command="$PC KEY {deviceId} {key}#" name="键值">
        <parameter name="key" maxValue="z" minValue="a" type="STRING"/>
      </operation>
      <operation command="$PC PLAY {deviceId} {cmd}#" name="播放">
        <parameter name="cmd" maxValue="4" minValue="1" type="INTEGER"/>
      </operation>
    </device>
    <device id="展区2-LIGHT-1" type="LIGHT">
      <operation command="$LIGHT ON {deviceId} {onoff}#" name="开关灯">
        <parameter name="onoff" maxValue="1" minValue="0" type="BOOLEAN"/>
      </operation>
      <operation command="$LIGHT {deviceId} {val}#" name="亮度">
        <parameter name="val" maxValue="100" minValue="0" type="INTEGER"/>
      </operation>
    </device>
    <timeline>
      <property name="unit" value="s"/>
      <property name="max" value="40"/>
      <timePoint tick="0">
        <command deviceId="展区1-PC-1" operationName="键值">
          <property name="key" value="b"/>
        </command>
      </timePoint>
      <timePoint tick="1">
        <command deviceId="展区1-PC-1" operationName="播放">
          <property name="cmd" value="2"/>
        </command>
      </timePoint>
      <timePoint tick="2">
        <command deviceId="展区1-LIGHT-1" operationName="开关灯">
          <property name="onoff" value="1"/>
        </command>
      </timePoint>
    </timeline>
  </area>
</exhibition>
