=== yuanxuegui/exhibition.models.common4Java/src/main/resources/exhibition-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.sec.ac.cn/exhibition-1.0" 
xmlns:tns="http://www.sec.ac.cn/exhibition-1.0" elementFormDefault="qualified">

    <element name="exhibition" type="tns:exhibitionType"></element>

    <complexType name="exhibitionType">
    	<sequence>
    		<element name="description" type="string"></element>
    		<element name="properties" type="tns:propertiesType"></element>
    		<element name="area" type="tns:areaType"></element>
    	</sequence>
    </complexType>

    <complexType name="propertiesType">
    	<sequence>
    		<element name="property" type="tns:propertyType"></element>
    	</sequence>
    </complexType>

    <complexType name="propertyType">
    	<sequence></sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="value" type="string"></attribute>
    </complexType>
    
    <complexType name="areaType">
    	<sequence>
    		<element name="devices" type="tns:devicesType"></element>
    		<element name="timeline" type="tns:timelineType"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    </complexType>
    
    <complexType name="devicesType">
    	<sequence>
    		<element name="device" type="tns:deviceType"></element>
    	</sequence>
    </complexType>
    
    <complexType name="timelineType">
    	<sequence>
    		<element name="properties" type="tns:propertiesType"></element>
    		<element name="timePoints" type="tns:timePointsType"></element>
    	</sequence>
    </complexType>
    
    <complexType name="deviceType">
    	<sequence>
    		<element name="operation" type="tns:operationType"></element>
    	</sequence>
    	<attribute name="id" type="string" use="required"></attribute>
    	<attribute name="type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="CURTAIN"></enumeration>
    				<enumeration value="LIGHT"></enumeration>
    				<enumeration value="SOMKE"></enumeration>
    				<enumeration value="WATER"></enumeration>
    				<enumeration value="FOG"></enumeration>
    				<enumeration value="SHADOW"></enumeration>
    				<enumeration value="PC"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>

    <complexType name="timePointsType">
    	<sequence>
    		<element name="timePoint" type="tns:timePointType"></element>
    	</sequence>
    </complexType>
    
    <complexType name="operationType">
    	<sequence>
    		<element name="parameter" type="tns:parameterType"></element>
    	</sequence>
    	<attribute name="name" type="string"></attribute>
    	<attribute name="command" type="string" use="required"></attribute>
    </complexType>

    <complexType name="parameterType">
    	<sequence>
    	</sequence>
    	<attribute name="type" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="boolean"></enumeration>
    				<enumeration value="integer"></enumeration>
    				<enumeration value="decimal"></enumeration>
    				<enumeration value="string"></enumeration>
    				<enumeration value="date"></enumeration>
    				<enumeration value="time"></enumeration>
    				<enumeration value="dateTime"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="name" type="string" use="required"></attribute>
    	<attribute name="sizeMin" type="int" use="optional"></attribute>
    	<attribute name="sizeMax" type="string" use="optional"></attribute>
    </complexType>

    <complexType name="timePointType">
    	<sequence>
    		<element name="command" type="tns:commandType"></element>
    	</sequence>
    	<attribute name="tick" type="int"></attribute>
    </complexType>

    <complexType name="commandType">
    	<sequence>
    		<element name="property" type="tns:propertyType"></element>
    	</sequence>
    	<attribute name="device-id" type="string"></attribute>
    	<attribute name="operation-name" type="string"></attribute>
    </complexType>
</schema>

=== yuanxuegui/exhibition.models.common4Java/src/main/resources/exhibition-1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<exhibition xmlns="http://www.sec.ac.cn/exhibition-1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.sec.ac.cn/exhibition-1.0 exhibition-1.0.xsd ">
	<description>某展示会</description>
	<properties>
		<property name="server.ip" value="192.168.1.2" />
		<property name="server.port" value="9090" />
	</properties>
	<area name="展区1">
		<devices>
			<device id="1-LIGHT-1" type="LIGHT">
				<operation command="$LIGHT ON {device-id} {on}#" name="开关">
					<parameter name="on" type="boolean" />
				</operation>
				<operation command="$LIGHT {device-id} {value}#" name="亮度">
					<parameter name="value" type="integer" sizeMin="0" sizeMax="100" />
				</operation>
			</device>
			<device id="1-PC-1" type="PC">
				<operation command="55 01 21 03 {device-id} {key}#" name="键值">
					<parameter name="key" type="integer" sizeMin="0" sizeMax="100" />
				</operation>
				<operation command="$PC VOL {device-id} {vol}#" name="音量">
					<parameter name="vol" type="integer" sizeMin="0" sizeMax="100" />
				</operation>
			</device>
		</devices>
		<timeline>
			<properties>
				<property name="unit" value="s" />
				<property name="max" value="40" />
			</properties>
			<timePoints>
				<timePoint tick="0">
					<command device-id="1-LIGHT-1" operation-name="开关">
						<property name="on" value="1" />
					</command>
				</timePoint>
				<timePoint tick="10">
					<command device-id="1-LIGHT-1" operation-name="亮度">
						<property name="value" value="50" />
					</command>
					<command device-id="1-PC-1" operation-name="键值">
						<property name="key" value="F2" />
					</command>
				</timePoint>
				<timePoint tick="20">
					<command device-id="1-PC-1" operation-name="音量">
						<property name="vol" value="100" />
					</command>
				</timePoint>
			</timePoints>
		</timeline>
	</area>
	<area name="展区2">
		<devices>
			<device id="1-LIGHT-1" type="LIGHT">
				<operation command="$LIGHT ON {device-id} {on}#" name="开关">
					<parameter name="on" type="boolean" />
				</operation>
				<operation command="$LIGHT {device-id} {value}#" name="亮度">
					<parameter name="value" type="integer" sizeMin="0" sizeMax="100" />
				</operation>
			</device>
			<device id="1-PC-1" type="PC">
				<operation command="$PC KEY {device-id} {key}#" name="键值">
					<parameter name="key" type="string" />
				</operation>
				<operation command="$PC VOL {device-id} {vol}#" name="音量">
					<parameter name="vol" type="integer" sizeMin="0" sizeMax="100" />
				</operation>
			</device>
		</devices>
		<timeline>
			<properties>
				<property name="unit" value="s" />
				<property name="max" value="40" />
			</properties>
			<timePoints>
				<timePoint tick="0">
					<command device-id="1-LIGHT-1" operation-name="开关">
						<property name="on" value="1" />
					</command>
				</timePoint>
				<timePoint tick="10">
					<command device-id="1-LIGHT-1" operation-name="亮度">
						<property name="value" value="50" />
					</command>
					<command device-id="1-PC-1" operation-name="键值">
						<property name="key" value="F2" />
					</command>
				</timePoint>
				<timePoint tick="50">
					<command device-id="1-PC-1" operation-name="音量">
						<property name="vol" value="100" />
					</command>
				</timePoint>
			</timePoints>
		</timeline>
	</area>
</exhibition>
